"""Regenerate lib/assent_consensus.py from the contract.

    python scripts/lift.py

The lifted module claims to be the agreement rules "as the contract runs them".
Maintaining it by hand makes that claim false the first time somebody edits one
side, and a copied rule that no deployed contract uses is worse than no copy at
all: it is a rule with a provenance it has not earned.

So the copy is generated, and tests/test_logic.py::TestLibParity compares the
two parsed trees function by function. Editing the contract and forgetting to
run this turns into a failing test rather than into a quiet lie.
"""

import ast
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "contracts" / "assent.py"
OUT = ROOT / "lib" / "assent_consensus.py"

CONSTANTS = ['RESIDUAL', 'SAME', 'CHANGED', 'UNCLEAR', 'FORMED', 'COUNTERED',
             'INDETERMINATE', 'VERDICTS', 'MAX_REASON']

FUNCTIONS = ['looks_like_address', 'clean_text', 'split_terms', 'normalise_token',
             'parse_vector', 'reconcile', 'popcount', 'resolve', 'render_mask',
             'parse_mask', 'structurally_sound', 'assent_agrees', 'sanitise_reason',
             'fence', 'number', 'build_prompt']

HEADER = '''# assent_consensus.py - the agreement rules, lifted out to be copied.
#
# GENERATED by scripts/lift.py from contracts/assent.py. Do not edit by hand:
# tests/test_logic.py compares the two parsed trees function by function, so an
# edit here fails the suite rather than quietly claiming a provenance it does
# not have.
#
# GenLayer contracts run as ONE Python file inside the GenVM. There is no pip
# install and no cross-file import at deploy time, so this is not a module you
# import: it is a curated block. contracts/assent.py already inlines these
# helpers. This file exists so the rules can be read and lifted into another
# project without reading a whole contract first.
#
# Everything here is pure. No storage, no network, no model. That is the point:
# these are the functions a validator runs to decide whether two nodes agreed,
# and a function that decides agreement must be deterministic or it decides
# nothing at all.
#
# assent_agrees is SYMMETRIC: agrees(a, b) == agrees(b, a).
#
# The idea worth lifting is resolve(). The leader asks the same rows in both
# presentation orders and folds them, a row the orders disagree on becomes
# unclear, and resolve() reduces the folded rows to the canonical outcome:
# countered with the changed rows named, indeterminate, or formed. Consensus
# compares exactly that tuple and exactly that tuple is stored, so agreement
# between nodes can never leave two different records behind.

# ---------------------------------------------------------------------------
# Deterministic helpers. Pure, module level, unit tested in tests/test_logic.py
# ---------------------------------------------------------------------------

'''


def main():
    src = CONTRACT.read_text(encoding="utf-8")
    tree = ast.parse(src)
    lines = src.splitlines(keepends=True)

    def segment(node):
        return "".join(lines[node.lineno - 1:node.end_lineno]).rstrip("\n")

    parts = []
    for name in CONSTANTS:
        for n in tree.body:
            if isinstance(n, ast.Assign) and any(
                    isinstance(t, ast.Name) and t.id == name for t in n.targets):
                parts.append(segment(n))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}")

    fns = []
    for name in FUNCTIONS:
        for n in tree.body:
            if isinstance(n, ast.FunctionDef) and n.name == name:
                fns.append(segment(n))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}()")

    OUT.write_text(
        HEADER + "\n".join(parts) + "\n\n\n" + "\n\n\n".join(fns) + "\n",
        encoding="utf-8", newline="\n",
    )
    print(f"  {OUT.relative_to(ROOT).as_posix()}: {len(CONSTANTS)} constants, "
          f"{len(FUNCTIONS)} functions")


if __name__ == "__main__":
    main()
